### ISSUE TITLE
fvm support

### ISSUE THREAD

**Issue by Antriadus** [lukepighetti/vscode_fast_build_runner#3]
Hi. Thanks for creating this great extension.
My only problem with this extension is that it does not support fvm.
Can you please add some kind of settings "useFvm" that will replace "dart run build_runner build --delete-conflicting-outputs..." with "fvm dart run build_runner build --delete-conflicting-outputs..."? That will be great

Greetings
Kamil

**Comment by lukepighetti** [comment]
Wait, people are actually using this? Haha. Please feel free to make a PR, shouldn't take too long.

**Comment by lukepighetti** [comment]
Maybe a "dartCommand" which defaults to "dart" and could be changed to "fvm dart"?

**Comment by misterfourtytwo** [comment]
It's a practice now to [set flutterSdk in the settings.json](https://fvm.app/docs/getting_started/configuration/#vs-code)
So, i created a [PR](https://github.com/lukepighetti/vscode_fast_build_runner/pull/5) to get sdk path from workspace settings, this way when jumping between projects with and without fvm plugin will always get right path.

**Comment by lukepighetti** [comment]
Closing as stale, please reopen if needed
